# This is a basic workflow to help you get started with Actions

name: Greeting from Lam Lok Hin

# Controls when the action will run. 
on: push
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print a greeting
        env: 
          MY_VAR: Hi there! My name is
          FIRST_NAME: Ryan
          LAST_NAME: Lam
        run: |
        
          echo $MY_VAR $FIRST_NAME $LAST_NAME.
